site_name: Open Source Cloud API
site_url: https://api.osaas.io
site_description: API Documentation for Open Source Cloud
site_author: Eyevinn Technology
nav:
  - Home: index.md
  - Client Libraries:
    - Javascript:
      - Core: sdk/javascript.md
      - Transcode: sdk/javascript-transcode.md
  - Command-Line Interface:
    - Usage: cli/usage.md
    - Commands: 
      - osc: cli/core.md
      - osc transcode: cli/transcode.md
      - osc packager: cli/packager.md
      - osc compare: cli/compare.md
      - osc intercom: cli/intercom.md
  - APIs:
    - FAST Engine API: services/channel-engine.md
    - Encore API: services/encore.md
theme:
  name: dracula
  logo: assets/logo_osc_512.png

use_directory_urls: false

copyright: Copyright &copy; 2023- <a href="https://www.eyevinn.se">Eyevinn Technology AB</a>
