site_name: Eyevinn Open Source Cloud API
site_url: https://osaas.docs.eyevinn.technology
site_description: API Documentation for Eyevinn Open Source Cloud
site_author: Eyevinn Technology
nav:
  - Home: index.md
  - APIs:
    - FAST Engine API: services/channel-engine.md
theme:
  name: dracula
  logo: assets/logo_eyevinn_256.png

copyright: Copyright &copy; 2023- <a href="https://www.eyevinn.se">Eyevinn Technology AB</a>
