site_name: Eyevinn Open Source Cloud API
site_url: https://api.osaas.io
site_description: API Documentation for Eyevinn Open Source Cloud
site_author: Eyevinn Technology
nav:
  - Home: index.md
  - APIs:
    - FAST Engine API: services/channel-engine.md
    - Encore API: services/encore.md
theme:
  name: dracula
  logo: assets/logo_osc_512.png

use_directory_urls: false

copyright: Copyright &copy; 2023- <a href="https://www.eyevinn.se">Eyevinn Technology AB</a>
